services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports: 
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
  
  user_service:
    build: .
    depends_on:
      - postgres
    ports: 
      - 8000:8000
    volumes:
      - ../user_service:/home/node/app
      - ../user_service/node_modules:/home/node/app/node_modules/
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      SECRET: ${SECRET}
      PORT: ${USER_PORT}

  gateway_service:
    build: ../software_gateway
    ports: 
      - 8001:8001
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules/
    environment:
      SECRET: ${SECRET}
      PORT: ${GATEWAY_PORT}
      USER_HOST: ${USER_HOST}
      USER_PORT: ${USER_PORT}
      DATA_STORAGE_HOST: ${DATA_STORAGE_HOST}
      DATA_STORAGE_PORT: ${DATA_STORAGE_PORT}
      UPDATE_HOST: ${UPDATE_HOST}
      UPDATE_PORT: ${UPDATE_PORT}

  eletronic_gateway:
    build: ../eletronic_gateway
    ports:
      - 8883:8883
    volumes:
      - ../eletronic_gateway:/home/node/app
      - ../eletronic_gateway/node_modules:/home/node/app/node_modules/
    environment:
      PORT: ${ELETRONIC_GATEWAY_PORT}

  data_storage:
    build: ../data_storage
    depends_on:
      - mongo
    ports:
      - 8002:8002
    volumes:
      - ../data_storage:/home/node/app
      - ../data_storage/node_modules:/home/node/app/node_modules/
    environment:
      PORT: ${DATA_STORAGE_PORT}
      MONGO_URI: ${MONGO_URI}
      MQTT_PORT: ${ELETRONIC_GATEWAY_PORT}
      MQTT_HOST: ${MQTT_HOST}
      MQTT_TOPIC: ${MQTT_TOPIC}
      PROCESSING_PORT: ${PROCESSING_PORT}
      PROCESSING_HOST: ${PROCESSING_HOST}
      USER_HOST: ${USER_HOST}
      USER_PORT: ${USER_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      MAIL_ENABLED: ${MAIL_ENABLED}

  update_service:
    build: ../updade_service
    depends_on:
      - mongo
    ports:
      - 8003:8003
    volumes:
      - ../updade_service:/home/node/app
      - ../updade_service/node_modules:/home/node/app/node_modules/
    environment:
      MONGO_URI: ${MONGO_URI}
      MQTT_PORT: ${ELETRONIC_GATEWAY_PORT}
      PORT: ${UPDATE_PORT}
  
  processing_service:
    build: ../processing_service
    entrypoint: python -m flask run --host=0.0.0.0 --port=${PROCESSING_PORT}
    ports:
      - 8004:8004
    volumes:
      - ../processing_service:/app
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
      PORT: ${PROCESSING_PORT}
      DATA_STORAGE_HOST: ${DATA_STORAGE_HOST}
      DATA_STORAGE_PORT: ${DATA_STORAGE_PORT}

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
  
